language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm install
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha ./tests/**.tests.js --reporter lcovonly -- -R spec
  - codecov
